tasks:
- init: composer install
  command: |
    cp .env.example .env
    # Check if environment variables are set in https://gitpod.io/variables.
    echo "Checking if environment variables are set ..."
    if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
      echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY, ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
      exit 1
    fi
    
    # Run the application
    echo "Starting application for '$path' in $(pwd)"
    php artisan key:generate && php artisan serve --port=8080

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  visibility: public

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
