version: '3.9'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-image
    command: >
      sh -c "php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
