version: '3.9'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-image:latest
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8080
