name: E2E (Playwright)

on:
  workflow_dispatch:
  #push:
  #pull_request:
  #  branches: [ main ]

jobs:
  checkout:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: setting environment variables
        run: export API_KEY="${{ secrets.API_KEY }}" && export MERCHANT_ACCOUNT=${{ secrets.MERCHANT_ACCOUNT }} && export CLIENT_KEY=${{ secrets.CLIENT_KEY }}
      - name: Start containers
        run: docker-compose -f "docker-compose.yaml" up -d --build
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Running docker-compose
        run: docker run --rm -p 8080:8080 -e API_KEY="${{ secrets.API_KEY }}" -e MERCHANT_ACCOUNT=${{ secrets.MERCHANT_ACCOUNT }} -e CLIENT_KEY=${{ secrets.CLIENT_KEY }} test-image 
      - name: Run testing suite
        run: docker run --rm --name adyen-testing-suite --network host ghcr.io/adyen-examples/adyen-testing-suite:v0.0.1
